version: '3.8'  # Use a more specific version if applicable

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount local backend code to the container  
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/socialMediaApp
    depends_on:
      - mongo
    stdin_open: true  # Keep stdin open even if not attached
    tty: true         # Allocate a pseudo-TTY
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Expose frontend port
    depends_on:
      - backend  # Ensure backend is started before frontend
    volumes:
      - ./frontend:/app  # Mount the frontend directory for live reloading

volumes:
  mongo-data:  # Define a named volume for MongoDB data
